name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publicar no servidor
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar conexão com banco
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          sed -i "s|__DB_HOST__|$DB_HOST|g" config/config.php
          sed -i "s|__DB_NAME__|$DB_NAME|g" config/config.php
          sed -i "s|__DB_USER__|$DB_USER|g" config/config.php
          sed -i "s|__DB_PASS__|$DB_PASS|g" config/config.php

      - name: Publicar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /coratech.totalh.net/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/database/**